<link rel="stylesheet" href="assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/pages/page-auth.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/plugins/forms/form-validation.css">
        <link
            rel="apple-touch-icon"
            href="assets/app-assets/images/ico/apple-icon-120.png">
        <link
            rel="shortcut icon"
            type="image/x-icon"
            href="assets/app-assets/images/ico/favicon.ico">
        <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600"
            rel="stylesheet">

        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/vendors/css/vendors.min.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/vendors/css/charts/apexcharts.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/bootstrap.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/bootstrap-extended.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/colors.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/components.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/themes/dark-layout.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/themes/bordered-layout.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/themes/semi-dark-layout.css">

        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/core/menu/menu-types/horizontal-menu.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/pages/dashboard-ecommerce.css">
        <link
            rel="stylesheet"
            type="text/css"
            href="assets/app-assets/css/plugins/charts/chart-apex.css">
        <link rel="stylesheet" type="text/css" href="assets/assets/css/style.css">